server:
  port: ${PORT:5000}
  
spring:
  rabbitmq:
    host: 192.168.126.219
    port: 30000
    username: guest
    password: guest

  datasource:
    initialize: false
    data: classpath:data.sql
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost/auth
    username: kian
    password: kian
    hikari:
      maximum-pool-size: 50
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
      
  cache:
    type: redis
      
management:
 security: 
   enabled: false
   
 ribbon:
  eureka:
    enabled: true  
   
logging:
  console: off
  file: ${logging.path}/uaa.log
  path: /var/log/uaa
  level:
    root: info
    org:
      kian:
        account:
          debug
  pattern:
    file: %d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n
    console: %d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n

app:
  name: Ecommerce-starter