server:  
  port: ${PORT:2222}

spring:
  rabbitmq:
    host: 172.17.0.2
    port: 30000
    username: guest
    password: guest
          
ribbon:
  eureka:
    enabled: true
    
test:
  accounts:
    - id: 1
      number: '0654321789'
      balance: 2500
      customerId: 1
    - id: 2
      number: '0654321780'
      balance: 0
      customerId: 1
    - id: 3
      number: '0650981789'
      balance: 12550
      customerId: 2