spring:
  application:
    name: admin
  rabbitmq:
    host: 192.168.126.219
    port: 30000
    username: guest
    password: guest
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine:
        clusters: TURBINE-CLUSTER
        location: monitoring
          
server: 
  port: 1111
security:
  user:
    name: admin
    password: admin123
  oauth2:
    client:
      accessTokenUri: http://localhost:9080/uaa/oauth/token
      userAuthorizationUri: http://localhost:9080/uaa/oauth/authorize
      clientId: ticketing-service
      clientSecret: 12345
      authorized-grant-types: authorization_code,refresh_token,password
    resource:
      userInfoUri: http://localhost:9080/uaa/users/current
eureka: 
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  security: 
    enabled: false